version: '3.7'
services:
  php:
    build: ./docker/php
    ports: ['9000:9000']
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['80:80']
    volumes: ['./symfony/:/var/www/symfony:cached']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    